import { lstat } from 'node:fs/promises'
import path from 'node:path'
import createTorrent from 'create-torrent'
import type { EgressPolicy } from './network-policy'
import {
  validateTorrentMetadata,
  type ValidatedTorrentMetadata
} from './torrent-metadata'

const TORRENT_CREATION_LIMITS = Object.freeze({
  commentBytes: 4_096,
  createdBy: 'WebTorrent Updated',
  nameBytes: 255
})

export type TorrentCreationErrorCode =
  | 'CREATION_FAILED'
  | 'INPUT_INVALID'
  | 'PRIVATE_TRACKER_REQUIRED'
  | 'SOURCE_NOT_AUTHORIZED'
  | 'TRACKER_REJECTED'

export class TorrentCreationError extends Error {
  readonly code: TorrentCreationErrorCode

  constructor(code: TorrentCreationErrorCode) {
    super(`Torrent creation failed: ${code}.`)
    this.name = 'TorrentCreationError'
    this.code = code
  }
}

export type TorrentCreationRequest = Readonly<{
  allowHttpTrackers: boolean
  announceTiers: ReadonlyArray<ReadonlyArray<string>>
  comment?: string
  filterJunkFiles: boolean
  name?: string
  private: boolean
  sourcePath: string
}>

export type TorrentCreationResult = Readonly<{
  metadata: ValidatedTorrentMetadata
  /** The parent of the selected source, so verified data seeds in place. */
  seedRoot: string
}>

export type TorrentCreationServiceOptions = Readonly<{
  create?: typeof createTorrent
  policy: EgressPolicy
  validate?: typeof validateTorrentMetadata
}>

const utf8Encoder = new TextEncoder()

/**
 * Creates a torrent from a selected file or directory.
 *
 * `client.seed()` is never used: WebTorrent 3.0.16 forces `skipVerify: true`
 * and creates an unreserved placeholder torrent before its info hash exists.
 * This produces validated v1 bytes first, so the caller can reserve the hash
 * and use the ordinary guarded add path with full verification.
 */
export class TorrentCreationService {
  readonly #create: typeof createTorrent
  readonly #policy: EgressPolicy
  readonly #validate: typeof validateTorrentMetadata

  constructor(options: TorrentCreationServiceOptions) {
    this.#create = options.create ?? createTorrent
    this.#policy = options.policy
    this.#validate = options.validate ?? validateTorrentMetadata
  }

  async create(
    request: TorrentCreationRequest
  ): Promise<TorrentCreationResult> {
    const sourcePath = this.#validateSourcePath(request.sourcePath)
    const tiers = this.#validateTrackers(request)
    this.#validateLabels(request)

    let stats
    try {
      stats = await lstat(sourcePath)
    } catch {
      throw new TorrentCreationError('SOURCE_NOT_AUTHORIZED')
    }
    // A symlinked source would let the created torrent describe data outside
    // the directory the user actually chose.
    if (stats.isSymbolicLink() || !(stats.isFile() || stats.isDirectory())) {
      throw new TorrentCreationError('SOURCE_NOT_AUTHORIZED')
    }

    const bytes = await new Promise<Uint8Array>((resolve, reject) => {
      this.#create(
        sourcePath,
        {
          announceList: tiers.map(tier => [...tier]),
          createdBy: TORRENT_CREATION_LIMITS.createdBy,
          filterJunkFiles: request.filterJunkFiles,
          private: request.private,
          ...(request.comment === undefined
            ? {}
            : { comment: request.comment }),
          ...(request.name === undefined ? {} : { name: request.name })
        },
        (error, torrent) => {
          if (error || !torrent) {
            reject(new TorrentCreationError('CREATION_FAILED'))
            return
          }
          resolve(torrent)
        }
      )
    })

    // The generated bytes re-enter through the ordinary raw metadata boundary:
    // creation is not a reason to skip path, geometry, or tracker validation.
    let metadata: ValidatedTorrentMetadata
    try {
      metadata = await this.#validate(bytes, this.#policy)
    } catch {
      throw new TorrentCreationError('CREATION_FAILED')
    }
    if (metadata.private !== request.private) {
      throw new TorrentCreationError('CREATION_FAILED')
    }

    return { metadata, seedRoot: path.dirname(sourcePath) }
  }

  #validateSourcePath(value: string): string {
    if (
      typeof value !== 'string' ||
      !path.isAbsolute(value) ||
      value.includes('\0') ||
      path.normalize(value) !== value ||
      path.dirname(value) === value
    ) {
      throw new TorrentCreationError('INPUT_INVALID')
    }
    return value
  }

  #validateLabels(request: TorrentCreationRequest): void {
    if (
      request.name !== undefined &&
      (request.name === '' ||
        request.name.includes('/') ||
        request.name.includes('\0') ||
        utf8Encoder.encode(request.name).byteLength >
          TORRENT_CREATION_LIMITS.nameBytes)
    ) {
      throw new TorrentCreationError('INPUT_INVALID')
    }
    if (
      request.comment !== undefined &&
      utf8Encoder.encode(request.comment).byteLength >
        TORRENT_CREATION_LIMITS.commentBytes
    ) {
      throw new TorrentCreationError('INPUT_INVALID')
    }
  }

  /**
   * `create-torrent` ships its own announce defaults; they are never product
   * policy. Only endpoints this engine can actually mediate are accepted.
   */
  #validateTrackers(
    request: TorrentCreationRequest
  ): ReadonlyArray<ReadonlyArray<string>> {
    const tiers: string[][] = []
    const seen = new Set<string>()
    for (const tier of request.announceTiers) {
      const validated: string[] = []
      for (const endpoint of tier) {
        let url: string
        try {
          url = this.#policy.validateTrackerUrl(endpoint)
        } catch {
          throw new TorrentCreationError('TRACKER_REJECTED')
        }
        if (!request.allowHttpTrackers && url.startsWith('http://')) {
          throw new TorrentCreationError('TRACKER_REJECTED')
        }
        if (seen.has(url)) continue
        seen.add(url)
        validated.push(url)
      }
      if (validated.length > 0) tiers.push(validated)
    }

    if (request.private && tiers.length === 0) {
      throw new TorrentCreationError('PRIVATE_TRACKER_REQUIRED')
    }
    return tiers
  }
}
